package com.massa.petmedtracking.util

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.massa.petmedtracking.domain.model.Medication
import com.massa.petmedtracking.domain.model.Pet
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class PdfGenerator(private val context: Context) {

    private val dateFormatter = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())

    fun generateMedicationHandout(pet: Pet, medications: List<Medication>): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        var yPos = 40f
        val margin = 40f
        val contentWidth = pageInfo.pageWidth - (2 * margin)

        // Title
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 24f
        canvas.drawText("Pet Medication Handout", margin, yPos, paint)
        yPos += 40f

        // Pet Information Header
        paint.textSize = 18f
        canvas.drawText("Pet Information", margin, yPos, paint)
        yPos += 25f

        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        paint.textSize = 12f
        canvas.drawText("Name: ${pet.name}", margin, yPos, paint)
        yPos += 20f
        canvas.drawText("Species: ${pet.species} (${pet.breed})", margin, yPos, paint)
        yPos += 20f
        canvas.drawText("Owner: ${pet.ownerName} - ${pet.ownerContact}", margin, yPos, paint)
        yPos += 40f

        // Medications Table Header
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 18f
        canvas.drawText("Medications", margin, yPos, paint)
        yPos += 25f

        // Draw Table Headers
        paint.textSize = 12f
        val col1 = margin
        val col2 = margin + 120f
        val col3 = margin + 200f
        val col4 = margin + 320f
        val col5 = margin + 420f

        canvas.drawText("Medicine", col1, yPos, paint)
        canvas.drawText("Dosage", col2, yPos, paint)
        canvas.drawText("Frequency", col3, yPos, paint)
        canvas.drawText("Start Date", col4, yPos, paint)
        canvas.drawText("Duration", col5, yPos, paint)
        yPos += 5f
        canvas.drawLine(margin, yPos, pageInfo.pageWidth.toFloat() - margin, yPos, paint)
        yPos += 20f

        // List Medications
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        for (medication in medications) {
            if (yPos > pageInfo.pageHeight - 50f) {
                // Simplified: basic single page for now
                break
            }
            canvas.drawText(medication.name, col1, yPos, paint)
            canvas.drawText(medication.dosage, col2, yPos, paint)
            canvas.drawText(medication.frequency.name.replace("_", " "), col3, yPos, paint)
            canvas.drawText(dateFormatter.format(medication.startDate), col4, yPos, paint)
            canvas.drawText("${medication.durationDays ?: "N/A"} days", col5, yPos, paint)
            yPos += 20f

            if (medication.notes.isNotBlank()) {
                paint.textSize = 10f
                paint.color = Color.DKGRAY
                canvas.drawText("Notes: ${medication.notes}", margin + 10f, yPos, paint)
                paint.textSize = 12f
                paint.color = Color.BLACK
                yPos += 20f
            }
            
            yPos += 10f
            if (yPos > pageInfo.pageHeight - 20f) break
        }

        // Footer
        yPos = pageInfo.pageHeight - 30f
        paint.textSize = 10f
        paint.color = Color.GRAY
        canvas.drawText("Generated by Pet Med Tracker - Accuracy is vital, follow all vet instructions.", margin, yPos, paint)

        pdfDocument.finishPage(page)

        val file = File(context.cacheDir, "${pet.name}_Medications.pdf")
        return try {
            val outputStream = FileOutputStream(file)
            pdfDocument.writeTo(outputStream)
            pdfDocument.close()
            outputStream.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
